In [ ]:
MULTIPLE LINEAR REGRESSION OLS MODEL(ORDINARY LEAST SQUARE MODEL)# OLS MODEL helps to minimize the square of the distance between 
#the actual values and the predicted values.

In [23]:
import pandas as pd

In [24]:
import numpy as np

In [25]:
import matplotlib.pyplot as plt 

In [26]:
import seaborn as sn

In [27]:
boston_data=pd.read_csv('D:\\python\\edureka\\DATASET\\additional_resources_6_xce_lwxlitn\\BostonHousing.csv')

In [28]:
boston_data

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [29]:
boston_data=boston_data.iloc[:,0:]

In [30]:
boston_data

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [31]:
x= boston_data.iloc[:,0:13]

In [32]:
x

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [34]:
y= boston_data.iloc[:,13]

In [35]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [36]:
x= boston_data.iloc[:,0:13].values

In [37]:
x

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [38]:
y= boston_data.iloc[:,13].values

In [39]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [40]:
x.shape

(506, 13)

In [41]:
y.shape

(506,)

In [42]:
from sklearn.model_selection import train_test_split # to split the data convert into array format i.e by .values 

In [43]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=111)

In [44]:
x_train

array([[3.15000e-02, 9.50000e+01, 1.47000e+00, ..., 1.70000e+01,
        3.96900e+02, 4.56000e+00],
       [1.14320e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.95580e+02, 7.67000e+00],
       [2.43938e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 2.82800e+01],
       ...,
       [1.55757e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.68740e+02, 1.81300e+01],
       [3.47428e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.54550e+02, 5.29000e+00],
       [6.15100e-02, 0.00000e+00, 5.19000e+00, ..., 2.02000e+01,
        3.96900e+02, 9.29000e+00]])

In [47]:
y_train

array([34.9, 26.5, 10.5, 20.8, 23.2, 10.4, 37.9,  7.2, 33.2, 24.4, 19.4,
       18.3, 18.9, 21.4, 15. , 23.7, 15.7, 32.5, 17.2, 32.4, 23.8, 20.7,
       31.5, 46. , 20. , 24.3, 10.2,  8.8, 16.1, 27.9,  8.3, 36.2, 26.6,
       15.2, 21. , 21.9, 19.9, 13.4, 22. , 18.8, 22. , 19.3, 33.1, 13.6,
       30.1, 33.2, 39.8, 22.7, 19.2, 28.4, 19.7, 23.1, 19.5,  5.6, 21.7,
       10.9, 29.8, 12.7, 19. , 21. , 16.6, 19.4, 21.7, 21.8, 16. , 25. ,
       27.5, 24.7, 37.2, 17.2, 13.4, 18.8, 10.9, 13.4, 23. , 18.5, 20. ,
       28.1, 10.8, 24.7, 23.7, 20.6, 34.9, 20.6, 37.3, 22.9, 22.8, 14.9,
       20.1, 35.4, 23.4, 18.9, 50. , 22.2, 37. , 33.1, 42.8, 15. , 23.1,
       19.4, 45.4, 12.7, 29. , 21.1, 18.4,  8.5, 26.6, 19.4, 50. , 20.6,
       13.1, 19.1, 50. , 24.7, 18.5, 26.4, 19.5, 21.2, 23. , 18.2,  7.5,
       17.8, 21.2, 22.8, 17.7, 24.5, 23.6, 23.9, 14.2, 28.6, 15.6, 17.5,
       31.6, 24.8, 13.8, 13.4, 22.9, 17.8, 19.6, 19.1, 16.2, 20.6, 16.8,
       50. , 18.9, 31.5, 30.5, 23.2, 24.5, 23.1, 33

In [53]:
import statsmodels.api as sm

In [54]:
x_train=np.array(x_train,dtype=float)

In [55]:
y_train=np.array(y_train,dtype=float)

In [56]:
x_train

array([[3.15000e-02, 9.50000e+01, 1.47000e+00, ..., 1.70000e+01,
        3.96900e+02, 4.56000e+00],
       [1.14320e-01, 0.00000e+00, 8.56000e+00, ..., 2.09000e+01,
        3.95580e+02, 7.67000e+00],
       [2.43938e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 2.82800e+01],
       ...,
       [1.55757e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.68740e+02, 1.81300e+01],
       [3.47428e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.54550e+02, 5.29000e+00],
       [6.15100e-02, 0.00000e+00, 5.19000e+00, ..., 2.02000e+01,
        3.96900e+02, 9.29000e+00]])

In [57]:
y_train

array([34.9, 26.5, 10.5, 20.8, 23.2, 10.4, 37.9,  7.2, 33.2, 24.4, 19.4,
       18.3, 18.9, 21.4, 15. , 23.7, 15.7, 32.5, 17.2, 32.4, 23.8, 20.7,
       31.5, 46. , 20. , 24.3, 10.2,  8.8, 16.1, 27.9,  8.3, 36.2, 26.6,
       15.2, 21. , 21.9, 19.9, 13.4, 22. , 18.8, 22. , 19.3, 33.1, 13.6,
       30.1, 33.2, 39.8, 22.7, 19.2, 28.4, 19.7, 23.1, 19.5,  5.6, 21.7,
       10.9, 29.8, 12.7, 19. , 21. , 16.6, 19.4, 21.7, 21.8, 16. , 25. ,
       27.5, 24.7, 37.2, 17.2, 13.4, 18.8, 10.9, 13.4, 23. , 18.5, 20. ,
       28.1, 10.8, 24.7, 23.7, 20.6, 34.9, 20.6, 37.3, 22.9, 22.8, 14.9,
       20.1, 35.4, 23.4, 18.9, 50. , 22.2, 37. , 33.1, 42.8, 15. , 23.1,
       19.4, 45.4, 12.7, 29. , 21.1, 18.4,  8.5, 26.6, 19.4, 50. , 20.6,
       13.1, 19.1, 50. , 24.7, 18.5, 26.4, 19.5, 21.2, 23. , 18.2,  7.5,
       17.8, 21.2, 22.8, 17.7, 24.5, 23.6, 23.9, 14.2, 28.6, 15.6, 17.5,
       31.6, 24.8, 13.8, 13.4, 22.9, 17.8, 19.6, 19.1, 16.2, 20.6, 16.8,
       50. , 18.9, 31.5, 30.5, 23.2, 24.5, 23.1, 33

In [58]:
regressor_ols=sm.OLS(endog=y_train,exog=x_train).fit()

In [59]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                      y   R-squared (uncentered):                   0.962
Model:                            OLS   Adj. R-squared (uncentered):              0.960
Method:                 Least Squares   F-statistic:                              661.7
Date:                Thu, 02 Feb 2023   Prob (F-statistic):                   7.56e-233
Time:                        21:16:22   Log-Likelihood:                         -1048.2
No. Observations:                 354   AIC:                                      2122.
Df Residuals:                     341   BIC:                                      2173.
Df Model:                          13                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.0759      0.048     -1.598      0.111      -0.169       0.018
x2             0.0424      0.018      2.390      0.017       0.007       0.077
x3            -0.0035      0.076     -0.047      0.963      -0.152       0.145
x4             1.3208      1.012      1.305      0.193      -0.670       3.312
x5             0.0871      3.948      0.022      0.982      -7.679       7.853
x6             5.7743      0.362     15.964      0.000       5.063       6.486
x7            -0.0178      0.015     -1.163      0.246      -0.048       0.012
x8            -0.8414      0.219     -3.848      0.000      -1.272      -0.411
x9             0.1065      0.075      1.417      0.157      -0.041       0.254
x10           -0.0078      0.005     -1.724      0.086      -0.017       0.001
x11           -0.4111      0.130     -3.157      0.002      -0.667      -0.155
x12            0.0154      0.003      4.933      0.000       0.009       0.021
x13           -0.4411      0.058     -7.618      0.000      -0.555      -0.327
==============================================================================
Omnibus:                      171.561   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1590.162
Skew:                           1.801   Prob(JB):                         0.00
Kurtosis:                      12.738   Cond. No.                     8.81e+03
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[3] The condition number is large, 8.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [60]:
pd.DataFrame(x_train)

0     1      2    3      4      5      6       7     8      9   \
0     0.03150  95.0   1.47  0.0  0.403  6.975   15.3  7.6534   3.0  402.0   
1     0.11432   0.0   8.56  0.0  0.520  6.781   71.3  2.8561   5.0  384.0   
2    24.39380   0.0  18.10  0.0  0.700  4.652  100.0  1.4672  24.0  666.0   
3     0.08707   0.0  12.83  0.0  0.437  6.140   45.8  4.0905   5.0  398.0   
4     0.07022   0.0   4.05  0.0  0.510  6.020   47.2  3.5549   5.0  296.0   
..        ...   ...    ...  ...    ...    ...    ...     ...   ...    ...   
349   0.05188   0.0   4.49  0.0  0.449  6.015   45.1  4.4272   3.0  247.0   
350   0.21719   0.0  10.59  1.0  0.489  5.807   53.8  3.6526   4.0  277.0   
351  15.57570   0.0  18.10  0.0  0.580  5.926   71.0  2.9084  24.0  666.0   
352   3.47428   0.0  18.10  1.0  0.718  8.780   82.9  1.9047  24.0  666.0   
353   0.06151   0.0   5.19  0.0  0.515  5.968   58.5  4.8122   5.0  224.0   

       10      11     12  
0    17.0  396.90   4.56  
1    20.9  395.58   7.67  
2    20.2  396.90  28.28  
3    18.7  386.96  10.27  
4    16.6  393.23  10.11  
..    ...     ...    ...  
349  18.5  395.99  12.86  
350  18.6  390.94  16.03  
351  20.2  368.74  18.13  
352  20.2  354.55   5.29  
353  20.2  396.90   9.29  

[354 rows x 13 columns]

In [ ]:
#introducing constant in the model

In [61]:
x_train=np.array(x_train,dtype=float)

In [62]:
y_train=np.array(y_train,dtype=float)

In [63]:
len(x_train)

354

In [64]:
len(y_train)

354

In [66]:
#introducing 1 in last column of each row
x_train=np.append(arr=x_train,values=np.ones((354,1)).astype(int),axis=1) 

In [68]:
pd.DataFrame(x_train)

0     1      2    3      4      5      6       7     8      9   \
0     0.03150  95.0   1.47  0.0  0.403  6.975   15.3  7.6534   3.0  402.0   
1     0.11432   0.0   8.56  0.0  0.520  6.781   71.3  2.8561   5.0  384.0   
2    24.39380   0.0  18.10  0.0  0.700  4.652  100.0  1.4672  24.0  666.0   
3     0.08707   0.0  12.83  0.0  0.437  6.140   45.8  4.0905   5.0  398.0   
4     0.07022   0.0   4.05  0.0  0.510  6.020   47.2  3.5549   5.0  296.0   
..        ...   ...    ...  ...    ...    ...    ...     ...   ...    ...   
349   0.05188   0.0   4.49  0.0  0.449  6.015   45.1  4.4272   3.0  247.0   
350   0.21719   0.0  10.59  1.0  0.489  5.807   53.8  3.6526   4.0  277.0   
351  15.57570   0.0  18.10  0.0  0.580  5.926   71.0  2.9084  24.0  666.0   
352   3.47428   0.0  18.10  1.0  0.718  8.780   82.9  1.9047  24.0  666.0   
353   0.06151   0.0   5.19  0.0  0.515  5.968   58.5  4.8122   5.0  224.0   

       10      11     12   13  
0    17.0  396.90   4.56  1.0  
1    20.9  395.58   7.67  1.0  
2    20.2  396.90  28.28  1.0  
3    18.7  386.96  10.27  1.0  
4    16.6  393.23  10.11  1.0  
..    ...     ...    ...  ...  
349  18.5  395.99  12.86  1.0  
350  18.6  390.94  16.03  1.0  
351  20.2  368.74  18.13  1.0  
352  20.2  354.55   5.29  1.0  
353  20.2  396.90   9.29  1.0  

[354 rows x 14 columns]

In [70]:
regressor_ols=sm.OLS(endog=y_train,exog=x_train).fit()

In [71]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.745
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     76.59
Date:                Thu, 02 Feb 2023   Prob (F-statistic):           1.38e-92
Time:                        21:24:49   Log-Likelihood:                -1030.9
No. Observations:                 354   AIC:                             2090.
Df Residuals:                     340   BIC:                             2144.
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.1092      0.046     -2.390      0.017      -0.199      -0.019
x2             0.0503      0.017      2.966      0.003       0.017       0.084
x3             0.0321      0.072      0.443      0.658      -0.110       0.175
x4             1.3426      0.965      1.391      0.165      -0.556       3.241
x5           -14.5043      4.500     -3.223      0.001     -23.355      -5.653
x6             3.6257      0.501      7.242      0.000       2.641       4.611
x7            -0.0092      0.015     -0.624      0.533      -0.038       0.020
x8            -1.3671      0.227     -6.032      0.000      -1.813      -0.921
x9             0.2502      0.076      3.306      0.001       0.101       0.399
x10           -0.0109      0.004     -2.498      0.013      -0.019      -0.002
x11           -0.9023      0.149     -6.042      0.000      -1.196      -0.609
x12            0.0097      0.003      3.112      0.002       0.004       0.016
x13           -0.5490      0.058     -9.442      0.000      -0.663      -0.435
const         35.0761      5.925      5.920      0.000      23.421      46.731
==============================================================================
Omnibus:                      150.164   Durbin-Watson:                   2.099
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              860.765
Skew:                           1.696   Prob(JB):                    1.22e-187
Kurtosis:                       9.845   Cond. No.                     1.55e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.55e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [73]:
boston_data

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [75]:
#drop the variables whose p>0.05, found here x3,x4,x7 i.e indus,chase,age

boston_data.drop(['indus','chas','age'],axis=1,inplace=True)

In [76]:
boston_data

crim    zn    nox     rm     dis  rad  tax  ptratio       b  lstat  \
0    0.00632  18.0  0.538  6.575  4.0900    1  296     15.3  396.90   4.98   
1    0.02731   0.0  0.469  6.421  4.9671    2  242     17.8  396.90   9.14   
2    0.02729   0.0  0.469  7.185  4.9671    2  242     17.8  392.83   4.03   
3    0.03237   0.0  0.458  6.998  6.0622    3  222     18.7  394.63   2.94   
4    0.06905   0.0  0.458  7.147  6.0622    3  222     18.7  396.90   5.33   
..       ...   ...    ...    ...     ...  ...  ...      ...     ...    ...   
501  0.06263   0.0  0.573  6.593  2.4786    1  273     21.0  391.99   9.67   
502  0.04527   0.0  0.573  6.120  2.2875    1  273     21.0  396.90   9.08   
503  0.06076   0.0  0.573  6.976  2.1675    1  273     21.0  396.90   5.64   
504  0.10959   0.0  0.573  6.794  2.3889    1  273     21.0  393.45   6.48   
505  0.04741   0.0  0.573  6.030  2.5050    1  273     21.0  396.90   7.88   

     medv  
0    24.0  
1    21.6  
2    34.7  
3    33.4  
4    36.2  
..    ...  
501  22.4  
502  20.6  
503  23.9  
504  22.0  
505  11.9  

[506 rows x 11 columns]

In [77]:
x=boston_data.iloc[:, 0:10] # last column will not print

In [78]:
x

crim    zn    nox     rm     dis  rad  tax  ptratio       b  lstat
0    0.00632  18.0  0.538  6.575  4.0900    1  296     15.3  396.90   4.98
1    0.02731   0.0  0.469  6.421  4.9671    2  242     17.8  396.90   9.14
2    0.02729   0.0  0.469  7.185  4.9671    2  242     17.8  392.83   4.03
3    0.03237   0.0  0.458  6.998  6.0622    3  222     18.7  394.63   2.94
4    0.06905   0.0  0.458  7.147  6.0622    3  222     18.7  396.90   5.33
..       ...   ...    ...    ...     ...  ...  ...      ...     ...    ...
501  0.06263   0.0  0.573  6.593  2.4786    1  273     21.0  391.99   9.67
502  0.04527   0.0  0.573  6.120  2.2875    1  273     21.0  396.90   9.08
503  0.06076   0.0  0.573  6.976  2.1675    1  273     21.0  396.90   5.64
504  0.10959   0.0  0.573  6.794  2.3889    1  273     21.0  393.45   6.48
505  0.04741   0.0  0.573  6.030  2.5050    1  273     21.0  396.90   7.88

[506 rows x 10 columns]

In [83]:
y= boston_data.iloc[:,10]

In [80]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [81]:
x=boston_data.iloc[:, 0:10].values

In [82]:
x

array([[6.3200e-03, 1.8000e+01, 5.3800e-01, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 4.6900e-01, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 4.6900e-01, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 5.7300e-01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 5.7300e-01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 5.7300e-01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [86]:
y= boston_data.iloc[:,10].values

In [87]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [88]:
from sklearn.model_selection import train_test_split

In [90]:
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.3, random_state=111)

In [91]:
x_train

array([[3.15000e-02, 9.50000e+01, 4.03000e-01, ..., 1.70000e+01,
        3.96900e+02, 4.56000e+00],
       [1.14320e-01, 0.00000e+00, 5.20000e-01, ..., 2.09000e+01,
        3.95580e+02, 7.67000e+00],
       [2.43938e+01, 0.00000e+00, 7.00000e-01, ..., 2.02000e+01,
        3.96900e+02, 2.82800e+01],
       ...,
       [1.55757e+01, 0.00000e+00, 5.80000e-01, ..., 2.02000e+01,
        3.68740e+02, 1.81300e+01],
       [3.47428e+00, 0.00000e+00, 7.18000e-01, ..., 2.02000e+01,
        3.54550e+02, 5.29000e+00],
       [6.15100e-02, 0.00000e+00, 5.15000e-01, ..., 2.02000e+01,
        3.96900e+02, 9.29000e+00]])

In [92]:
x_train=np.array(x_train,dtype=float)

In [93]:
x_train

array([[3.15000e-02, 9.50000e+01, 4.03000e-01, ..., 1.70000e+01,
        3.96900e+02, 4.56000e+00],
       [1.14320e-01, 0.00000e+00, 5.20000e-01, ..., 2.09000e+01,
        3.95580e+02, 7.67000e+00],
       [2.43938e+01, 0.00000e+00, 7.00000e-01, ..., 2.02000e+01,
        3.96900e+02, 2.82800e+01],
       ...,
       [1.55757e+01, 0.00000e+00, 5.80000e-01, ..., 2.02000e+01,
        3.68740e+02, 1.81300e+01],
       [3.47428e+00, 0.00000e+00, 7.18000e-01, ..., 2.02000e+01,
        3.54550e+02, 5.29000e+00],
       [6.15100e-02, 0.00000e+00, 5.15000e-01, ..., 2.02000e+01,
        3.96900e+02, 9.29000e+00]])

In [94]:
y_train=np.array(y_train,dtype=float)

In [95]:
y_train

array([34.9, 26.5, 10.5, 20.8, 23.2, 10.4, 37.9,  7.2, 33.2, 24.4, 19.4,
       18.3, 18.9, 21.4, 15. , 23.7, 15.7, 32.5, 17.2, 32.4, 23.8, 20.7,
       31.5, 46. , 20. , 24.3, 10.2,  8.8, 16.1, 27.9,  8.3, 36.2, 26.6,
       15.2, 21. , 21.9, 19.9, 13.4, 22. , 18.8, 22. , 19.3, 33.1, 13.6,
       30.1, 33.2, 39.8, 22.7, 19.2, 28.4, 19.7, 23.1, 19.5,  5.6, 21.7,
       10.9, 29.8, 12.7, 19. , 21. , 16.6, 19.4, 21.7, 21.8, 16. , 25. ,
       27.5, 24.7, 37.2, 17.2, 13.4, 18.8, 10.9, 13.4, 23. , 18.5, 20. ,
       28.1, 10.8, 24.7, 23.7, 20.6, 34.9, 20.6, 37.3, 22.9, 22.8, 14.9,
       20.1, 35.4, 23.4, 18.9, 50. , 22.2, 37. , 33.1, 42.8, 15. , 23.1,
       19.4, 45.4, 12.7, 29. , 21.1, 18.4,  8.5, 26.6, 19.4, 50. , 20.6,
       13.1, 19.1, 50. , 24.7, 18.5, 26.4, 19.5, 21.2, 23. , 18.2,  7.5,
       17.8, 21.2, 22.8, 17.7, 24.5, 23.6, 23.9, 14.2, 28.6, 15.6, 17.5,
       31.6, 24.8, 13.8, 13.4, 22.9, 17.8, 19.6, 19.1, 16.2, 20.6, 16.8,
       50. , 18.9, 31.5, 30.5, 23.2, 24.5, 23.1, 33

In [96]:
x_train=np.append(arr=x_train,values=np.ones((354,1)).astype(int),axis=1)

In [97]:
x_train

array([[3.15000e-02, 9.50000e+01, 4.03000e-01, ..., 3.96900e+02,
        4.56000e+00, 1.00000e+00],
       [1.14320e-01, 0.00000e+00, 5.20000e-01, ..., 3.95580e+02,
        7.67000e+00, 1.00000e+00],
       [2.43938e+01, 0.00000e+00, 7.00000e-01, ..., 3.96900e+02,
        2.82800e+01, 1.00000e+00],
       ...,
       [1.55757e+01, 0.00000e+00, 5.80000e-01, ..., 3.68740e+02,
        1.81300e+01, 1.00000e+00],
       [3.47428e+00, 0.00000e+00, 7.18000e-01, ..., 3.54550e+02,
        5.29000e+00, 1.00000e+00],
       [6.15100e-02, 0.00000e+00, 5.15000e-01, ..., 3.96900e+02,
        9.29000e+00, 1.00000e+00]])

In [98]:
regressor_ols=sm.OLS(endog=y_train,exog=x_train).fit()

In [99]:
regressor_ols.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.743
Model:                            OLS   Adj. R-squared:                  0.736
Method:                 Least Squares   F-statistic:                     99.41
Date:                Thu, 02 Feb 2023   Prob (F-statistic):           5.47e-95
Time:                        21:44:27   Log-Likelihood:                -1032.2
No. Observations:                 354   AIC:                             2086.
Df Residuals:                     343   BIC:                             2129.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -0.1144      0.046     -2.513      0.012      -0.204      -0.025
x2             0.0515      0.016      3.127      0.002       0.019       0.084
x3           -14.2850      4.117     -3.470      0.001     -22.382      -6.188
x4             3.6147      0.489      7.394      0.000       2.653       4.576
x5            -1.3719      0.218     -6.284      0.000      -1.801      -0.943
x6             0.2532      0.070      3.601      0.000       0.115       0.391
x7            -0.0106      0.004     -2.855      0.005      -0.018      -0.003
x8            -0.9187      0.148     -6.224      0.000      -1.209      -0.628
x9             0.0098      0.003      3.157      0.002       0.004       0.016
x10           -0.5574      0.055    -10.144      0.000      -0.666      -0.449
const         35.0953      5.871      5.977      0.000      23.547      46.644
==============================================================================
Omnibus:                      147.019   Durbin-Watson:                   2.090
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              798.116
Skew:                           1.675   Prob(JB):                    4.91e-174
Kurtosis:                       9.549   Cond. No.                     1.50e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.5e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
# now the model contains adj.r2 vaules. that means its centered. 